spring.application.name=JwelleryShop-BE

#spring.mongodb.uri=mongodb://localhost:27017/jwelleryshop_ecommerce
spring.mongodb.uri=${DB_URL:5001}
server.port=${PORT}
logging.level.org.springframework=debug
spring.data.mongodb.auto-index-creation=true

# Cloudinary Configuration
cloudinary.cloud-name=${cloudinaryName}
cloudinary.api-key=${cloudinaryAPIKEY}
cloudinary.api-secret=${cloudinaryAPISECRET}
# Increase Multipart File Upload Limits (Allows up to 10MB images)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

goldapi.key=${GOLDAPI}